name: 'Chromatic CI/CD'

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.stories.tsx'
  push:
    branches: [main]
    paths:
      - '**/*.stories.tsx'

jobs:
  chromatic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Chromatic Publish
        id: publish_chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          onlyChanged: true
